# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BASICDETAILS.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
#STUDENT_LOGIN_ID ,STUDENT_ID ,FIRST_NAME ,LAST_NAME ,D.O.B ,GENDER ,EMAIL ,CONTACT_NUM ,ADDRESS1,ADDRESS2 ,PIN ,COURSECODE


from PyQt4 import QtCore, QtGui
import sqlite3
from GRPA import Ui_Dialog2
from GRPB import Ui_Dialog3

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog1(object):
    def showMessageBox(self,message):
        msgBox = QtGui.QMessageBox()
        msgBox.setIcon(QtGui.QMessageBox.Warning)
        
        msgBox.setText(message)
        msgBox.setStandardButtons(QtGui.QMessageBox.Ok)
        msgBox.exec_()
    def insertData(self):
        STUDENT_LOGIN_ID = self.STUDENTLOGINlineEdit.text()
        STUDENT_ID = self.lineEdit_2.text()
        FIRST_NAME= self.lineEdit_3.text()
        LAST_NAME=self.lineEdit_4.text()
        #D.O.B=self.dateEdit.text()
        #GENDER=self.MALEradioButton.setOn()
        EMAIL=self.lineEdit_5.text()
        CONTACT_NUM=self.lineEdit_6.text()
        ADDRESS1=self.lineEdit_7.text()
        ADDRESS2=self.lineEdit_8.text()
        PIN=self.lineEdit_9.text()
        COURSECODE=self.lineEdit_10.text()

        connection  = sqlite3.connect("login1.db")
        connection.execute("INSERT INTO USERS VALUES(?,?,?,?,?,?,?,?,?,?)",(STUDENT_LOGIN_ID ,STUDENT_ID ,FIRST_NAME ,LAST_NAME ,EMAIL ,CONTACT_NUM ,ADDRESS1,ADDRESS2 ,PIN ,COURSECODE))
        connection.commit()
        connection.close()
    
        CODE = self.lineEdit_10.text()
        
        if(CODE == 'A'):
            print("GROUP A ! ")
            self.lineEdit_10Window = QtGui.QDialog()
            self.ui = Ui_Dialog2()
            self.ui.setupUi(self.lineEdit_10Window)
            self.lineEdit_10Window.show()
    

        elif(CODE =='B'):
            self.lineEdit_10Window = QtGui.QDialog()
            self.ui = Ui_Dialog3()
            self.ui.setupUi(self.lineEdit_10Window)
            self.lineEdit_10Window.show()
        else:
           print("no course code ?")
           self.showMessageBox('ENTER COURSE CODE (A / B)')



        
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1303, 911)
        Dialog.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 255, 255);"))
        self.ROLL_NUMLBL = QtGui.QLabel(Dialog)
        self.ROLL_NUMLBL.setGeometry(QtCore.QRect(30, 10, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ROLL_NUMLBL.setFont(font)
        self.ROLL_NUMLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.ROLL_NUMLBL.setObjectName(_fromUtf8("ROLL_NUMLBL"))
        self.STUDENTIDframe = QtGui.QFrame(Dialog)
        self.STUDENTIDframe.setGeometry(QtCore.QRect(30, 40, 681, 80))
        self.STUDENTIDframe.setFrameShape(QtGui.QFrame.Box)
        self.STUDENTIDframe.setFrameShadow(QtGui.QFrame.Sunken)
        self.STUDENTIDframe.setLineWidth(2)
        self.STUDENTIDframe.setMidLineWidth(1)
        self.STUDENTIDframe.setObjectName(_fromUtf8("STUDENTIDframe"))
        self.STUDENTLOGINLBL = QtGui.QLabel(self.STUDENTIDframe)
        self.STUDENTLOGINLBL.setGeometry(QtCore.QRect(30, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.STUDENTLOGINLBL.setFont(font)
        self.STUDENTLOGINLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.STUDENTLOGINLBL.setObjectName(_fromUtf8("STUDENTLOGINLBL"))
        self.STUDENTLOGINlineEdit = QtGui.QLineEdit(self.STUDENTIDframe)
        self.STUDENTLOGINlineEdit.setGeometry(QtCore.QRect(350, 20, 321, 41))
        self.STUDENTLOGINlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.STUDENTLOGINlineEdit.setObjectName(_fromUtf8("STUDENTLOGINlineEdit"))
        self.BASICDETAILSFRAME = QtGui.QFrame(Dialog)
        self.BASICDETAILSFRAME.setGeometry(QtCore.QRect(30, 160, 1261, 671))
        self.BASICDETAILSFRAME.setFrameShape(QtGui.QFrame.Box)
        self.BASICDETAILSFRAME.setFrameShadow(QtGui.QFrame.Sunken)
        self.BASICDETAILSFRAME.setLineWidth(2)
        self.BASICDETAILSFRAME.setMidLineWidth(2)
        self.BASICDETAILSFRAME.setObjectName(_fromUtf8("BASICDETAILSFRAME"))
        self.INFORMATIONLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.INFORMATIONLBL.setGeometry(QtCore.QRect(20, 10, 651, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.INFORMATIONLBL.setFont(font)
        self.INFORMATIONLBL.setObjectName(_fromUtf8("INFORMATIONLBL"))
        self.STUDENTIDLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.STUDENTIDLBL.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.STUDENTIDLBL.setFont(font)
        self.STUDENTIDLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.STUDENTIDLBL.setObjectName(_fromUtf8("STUDENTIDLBL"))
        self.FIRSTNAMELBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.FIRSTNAMELBL.setGeometry(QtCore.QRect(20, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FIRSTNAMELBL.setFont(font)
        self.FIRSTNAMELBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.FIRSTNAMELBL.setObjectName(_fromUtf8("FIRSTNAMELBL"))
        self.LASTNAMELBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.LASTNAMELBL.setGeometry(QtCore.QRect(20, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LASTNAMELBL.setFont(font)
        self.LASTNAMELBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.LASTNAMELBL.setObjectName(_fromUtf8("LASTNAMELBL"))
        self.DOBLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.DOBLBL.setGeometry(QtCore.QRect(20, 260, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DOBLBL.setFont(font)
        self.DOBLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.DOBLBL.setObjectName(_fromUtf8("DOBLBL"))
        self.GENDERLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.GENDERLBL.setGeometry(QtCore.QRect(20, 320, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.GENDERLBL.setFont(font)
        self.GENDERLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.GENDERLBL.setObjectName(_fromUtf8("GENDERLBL"))
        self.EMAILLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.EMAILLBL.setGeometry(QtCore.QRect(20, 370, 101, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.EMAILLBL.setFont(font)
        self.EMAILLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.EMAILLBL.setObjectName(_fromUtf8("EMAILLBL"))
        self.CONTACTNUMLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.CONTACTNUMLBL.setGeometry(QtCore.QRect(20, 420, 201, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CONTACTNUMLBL.setFont(font)
        self.CONTACTNUMLBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.CONTACTNUMLBL.setObjectName(_fromUtf8("CONTACTNUMLBL"))
        self.ADDRESSL1LBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.ADDRESSL1LBL.setGeometry(QtCore.QRect(20, 475, 201, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ADDRESSL1LBL.setFont(font)
        self.ADDRESSL1LBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.ADDRESSL1LBL.setObjectName(_fromUtf8("ADDRESSL1LBL"))
        self.ADDRESSL2LBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.ADDRESSL2LBL.setGeometry(QtCore.QRect(20, 530, 201, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ADDRESSL2LBL.setFont(font)
        self.ADDRESSL2LBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.ADDRESSL2LBL.setObjectName(_fromUtf8("ADDRESSL2LBL"))
        self.PINCODELBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.PINCODELBL.setGeometry(QtCore.QRect(20, 590, 161, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PINCODELBL.setFont(font)
        self.PINCODELBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.PINCODELBL.setObjectName(_fromUtf8("PINCODELBL"))
        self.COURSELBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.COURSELBL.setGeometry(QtCore.QRect(20, 630, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.COURSELBL.setFont(font)
        self.COURSELBL.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);"))
        self.COURSELBL.setObjectName(_fromUtf8("COURSELBL"))
        self.lineEdit_2 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 90, 211, 22))
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 150, 211, 22))
        self.lineEdit_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 200, 211, 22))
        self.lineEdit_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.dateEdit = QtGui.QDateEdit(self.BASICDETAILSFRAME)
        self.dateEdit.setGeometry(QtCore.QRect(240, 260, 211, 31))
        self.dateEdit.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);background-color: rgb(255, 255, 255);"))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.MALEradioButton = QtGui.QRadioButton(self.BASICDETAILSFRAME)
        self.MALEradioButton.setGeometry(QtCore.QRect(240, 320, 95, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MALEradioButton.setFont(font)
        self.MALEradioButton.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.MALEradioButton.setObjectName(_fromUtf8("MALEradioButton"))
        self.FEMALEradioButton = QtGui.QRadioButton(self.BASICDETAILSFRAME)
        self.FEMALEradioButton.setGeometry(QtCore.QRect(370, 319, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FEMALEradioButton.setFont(font)
        self.FEMALEradioButton.setStyleSheet(_fromUtf8("color: rgb(255, 85, 255);"))
        self.FEMALEradioButton.setObjectName(_fromUtf8("FEMALEradioButton"))
        self.lineEdit_5 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 371, 431, 31))
        self.lineEdit_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 421, 201, 31))
        self.lineEdit_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_7.setGeometry(QtCore.QRect(240, 471, 431, 31))
        self.lineEdit_7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 531, 431, 31))
        self.lineEdit_8.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_9.setGeometry(QtCore.QRect(240, 581, 201, 31))
        self.lineEdit_9.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.BASICDETAILSFRAME)
        self.lineEdit_10.setGeometry(QtCore.QRect(240, 630, 201, 31))
        self.lineEdit_10.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        ####################################################################
  #      self.lineEdit_10.text.connect(self.COURSECheck)
        ###################################################
        self.CREATEPUSHBUTTN = QtGui.QPushButton(self.BASICDETAILSFRAME)
        self.CREATEPUSHBUTTN.setGeometry(QtCore.QRect(890, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CREATEPUSHBUTTN.setFont(font)
        self.CREATEPUSHBUTTN.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.CREATEPUSHBUTTN.setObjectName(_fromUtf8("CREATEPUSHBUTTN"))
        self.UPDATEpushButton = QtGui.QPushButton(self.BASICDETAILSFRAME)
        self.UPDATEpushButton.setGeometry(QtCore.QRect(1070, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UPDATEpushButton.setFont(font)
        self.UPDATEpushButton.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.UPDATEpushButton.setObjectName(_fromUtf8("UPDATEpushButton"))
        self.CLEARpushButton = QtGui.QPushButton(self.BASICDETAILSFRAME)
        self.CLEARpushButton.setGeometry(QtCore.QRect(890, 550, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CLEARpushButton.setFont(font)
        self.CLEARpushButton.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);background-color: rgb(255, 255, 255);"))
        self.CLEARpushButton.setObjectName(_fromUtf8("CLEARpushButton"))
        self.DELETEpushButton = QtGui.QPushButton(self.BASICDETAILSFRAME)
        self.DELETEpushButton.setGeometry(QtCore.QRect(1070, 550, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DELETEpushButton.setFont(font)
        self.DELETEpushButton.setStyleSheet(_fromUtf8("color: rgb(85, 0, 0);background-color: rgb(255, 255, 255);"))
        self.DELETEpushButton.setObjectName(_fromUtf8("DELETEpushButton"))
        self.STUPICLBL = QtGui.QLabel(self.BASICDETAILSFRAME)
        self.STUPICLBL.setGeometry(QtCore.QRect(890, 30, 301, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.STUPICLBL.setFont(font)
        self.STUPICLBL.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);background-color: rgb(255, 255, 255);"))
        self.STUPICLBL.setFrameShape(QtGui.QFrame.Box)
        self.STUPICLBL.setFrameShadow(QtGui.QFrame.Raised)
        self.STUPICLBL.setLineWidth(2)
        self.STUPICLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.STUPICLBL.setObjectName(_fromUtf8("STUPICLBL"))
        self.COUNTERlcdNumber = QtGui.QLCDNumber(Dialog)
        self.COUNTERlcdNumber.setGeometry(QtCore.QRect(1120, 10, 171, 111))
        self.COUNTERlcdNumber.setStyleSheet(_fromUtf8("color: rgb(0, 85, 127);"))
        self.COUNTERlcdNumber.setObjectName(_fromUtf8("COUNTERlcdNumber"))
        self.SUBMITpushButton = QtGui.QPushButton(Dialog)
        self.SUBMITpushButton.setGeometry(QtCore.QRect(580, 840, 201, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMITpushButton.setFont(font)
        self.SUBMITpushButton.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);background-color: rgb(255, 255, 255);"))
        self.SUBMITpushButton.setObjectName(_fromUtf8("SUBMITpushButton"))
        ################################################################
        self.SUBMITpushButton.clicked.connect(self.insertData)
        ##################################################################
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.ROLL_NUMLBL.setText(_translate("Dialog", "ROLL NUMBER", None))
        self.STUDENTLOGINLBL.setText(_translate("Dialog", "STUDENT LOGIN ID", None))
        self.INFORMATIONLBL.setText(_translate("Dialog", "S T U D E N T    I N F O R M A T I O N", None))
        self.STUDENTIDLBL.setText(_translate("Dialog", "STUDENT ID", None))
        self.FIRSTNAMELBL.setText(_translate("Dialog", "FIRST NAME", None))
        self.LASTNAMELBL.setText(_translate("Dialog", "LAST NAME", None))
        self.DOBLBL.setText(_translate("Dialog", "DATE OF BIRTH", None))
        self.GENDERLBL.setText(_translate("Dialog", "GENDER", None))
        self.EMAILLBL.setText(_translate("Dialog", "EMAIL", None))
        self.CONTACTNUMLBL.setText(_translate("Dialog", "CONTACT NUMBER", None))
        self.ADDRESSL1LBL.setText(_translate("Dialog", "ADDRESS LINE 1", None))
        self.ADDRESSL2LBL.setText(_translate("Dialog", "ADDRESS LINE 2", None))
        self.PINCODELBL.setText(_translate("Dialog", "PINCODE", None))
        self.COURSELBL.setText(_translate("Dialog", "COURSE CODE", None))
        self.MALEradioButton.setText(_translate("Dialog", "MALE", None))
        self.FEMALEradioButton.setText(_translate("Dialog", "FEMALE", None))
        self.CREATEPUSHBUTTN.setText(_translate("Dialog", "CREATE", None))
        self.UPDATEpushButton.setText(_translate("Dialog", "UPDATE", None))
        self.CLEARpushButton.setText(_translate("Dialog", "CLEAR", None))
        self.DELETEpushButton.setText(_translate("Dialog", "DELETE", None))
        self.STUPICLBL.setText(_translate("Dialog", "CLICK TO PROVIDE IMAGE", None))
        self.SUBMITpushButton.setText(_translate("Dialog", "SUBMIT", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

