# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GRPA.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sqlite3

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog2(object):
    def showMessageBox(self,message):
        msgBox = QtGui.QMessageBox()
        msgBox.setIcon(QtGui.QMessageBox.Warning)
        
        msgBox.setText(message)
        msgBox.setStandardButtons(QtGui.QMessageBox.Ok)
        msgBox.exec_()
    def SUBMITApushButtonCheck(self):
        
        self.showMessageBox('SUCCESSFULLY ENTERED MARKS')
    
    
        STUDENT_ID = self.STUDENTIDlineEdit.text()
        DIV = self.DIVlineEdit.text()
        ############################ PHYSICS 
        ATTPHY= self.ATTPHYlineEdit.text()
        UTPHY=self.UTPHYlineEdit.text()
        SEMPHY=self.SEMPHYlineEdit.text()
        GRADEPHY=self.GRADEPHYlineEdit.text()
        ############################ CHEMISTRY
        ATTCHEM= self.ATTCHMlineEdit.text()
        UTCHEM=self.UTCHMlineEdit.text()
        SEMCHEM=self.SEMCHMlineEdit.text()
        GRADECHEM=self.GRADECHMlineEdit.text()
        ############################ MATHS
        ATTMAT= self.ATTMATHlineEdit.text()
        UTMAT=self.UTMATHlineEdit.text()
        SEMMAT=self.SEMMATHlineEdit.text()
        GRADEMAT=self.GRADEMATHlineEdit.text()
        ############################ BEEE
        ATTBEEE= self.ATTBElineEdit.text()
        UTBEEE=self.UTBElineEdit.text()
        SEMBEEE=self.SEMBElineEdit.text()
        GRADEBEEE=self.GRADEBElineEdit.text()
        ############################ EG
        ATTEG= self.ATTEGlineEdit.text()
        UTEG=self.UTEGlineEdit.text()
        SEMEG=self.SEMEGlineEdit.text()
        GRADEEG=self.SEMEGlineEdit_2.text()
        ############################ CS
        ATTCS= self.ATTCSlineEdit.text()
        UTCS=self.UTCSlineEdit.text()
        SEMCS=self.SEMCSlineEdit.text()
        GRADECS=self.GRADECSlineEdit.text()
        

        connection  = sqlite3.connect("FYBTECH_A.db")
        connection.execute("INSERT INTO PHYSICS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTPHY,UTPHY,SEMPHY,GRADEPHY))
        connection.execute("INSERT INTO MATHS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTCHEM,UTCHEM,SEMCHEM,GRADECHEM))
        connection.execute("INSERT INTO CHEMISTRY VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTMAT,UTMAT,SEMMAT,GRADEMAT))
        connection.execute("INSERT INTO BEEE VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTBEEE,UTBEEE,SEMBEEE,GRADEBEEE))
        connection.execute("INSERT INTO EG VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTEG,UTEG,SEMEG,GRADEEG))
        connection.execute("INSERT INTO CS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTCS,UTCS,SEMCS,GRADECS))                                                         
        connection.commit()
        connection.close()
        self.SUBMITApushButton.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1312, 849)
        Dialog.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);"))
        self.STUDENTDATALBL = QtGui.QLabel(Dialog)
        self.STUDENTDATALBL.setGeometry(QtCore.QRect(210, 20, 1011, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.STUDENTDATALBL.setFont(font)
        self.STUDENTDATALBL.setObjectName(_fromUtf8("STUDENTDATALBL"))
        self.GRPAframe = QtGui.QFrame(Dialog)
        self.GRPAframe.setGeometry(QtCore.QRect(10, 60, 1291, 771))
        self.GRPAframe.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);"))
        self.GRPAframe.setFrameShape(QtGui.QFrame.Box)
        self.GRPAframe.setFrameShadow(QtGui.QFrame.Sunken)
        self.GRPAframe.setLineWidth(2)
        self.GRPAframe.setMidLineWidth(2)
        self.GRPAframe.setObjectName(_fromUtf8("GRPAframe"))
        self.STUDENTIDLBL = QtGui.QLabel(self.GRPAframe)
        self.STUDENTIDLBL.setGeometry(QtCore.QRect(50, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.STUDENTIDLBL.setFont(font)
        self.STUDENTIDLBL.setObjectName(_fromUtf8("STUDENTIDLBL"))
        self.STUDENTIDlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.STUDENTIDlineEdit.setGeometry(QtCore.QRect(260, 20, 261, 31))
        self.STUDENTIDlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.STUDENTIDlineEdit.setObjectName(_fromUtf8("STUDENTIDlineEdit"))
        self.PHYSICSLBL = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL.setGeometry(QtCore.QRect(490, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL.setFont(font)
        self.PHYSICSLBL.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL.setObjectName(_fromUtf8("PHYSICSLBL"))
        self.DIVLBL = QtGui.QLabel(self.GRPAframe)
        self.DIVLBL.setGeometry(QtCore.QRect(780, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DIVLBL.setFont(font)
        self.DIVLBL.setObjectName(_fromUtf8("DIVLBL"))
        self.DIVlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.DIVlineEdit.setGeometry(QtCore.QRect(830, 21, 241, 31))
        self.DIVlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.DIVlineEdit.setObjectName(_fromUtf8("DIVlineEdit"))
        self.ATTPHYLBL = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL.setGeometry(QtCore.QRect(40, 120, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL.setFont(font)
        self.ATTPHYLBL.setObjectName(_fromUtf8("ATTPHYLBL"))
        self.ATTPHYlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTPHYlineEdit.setGeometry(QtCore.QRect(190, 120, 141, 31))
        self.ATTPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTPHYlineEdit.setObjectName(_fromUtf8("ATTPHYlineEdit"))
        self.UTLBL = QtGui.QLabel(self.GRPAframe)
        self.UTLBL.setGeometry(QtCore.QRect(430, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL.setFont(font)
        self.UTLBL.setObjectName(_fromUtf8("UTLBL"))
        self.UTPHYlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTPHYlineEdit.setGeometry(QtCore.QRect(480, 120, 131, 31))
        self.UTPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTPHYlineEdit.setObjectName(_fromUtf8("UTPHYlineEdit"))
        self.label = QtGui.QLabel(self.GRPAframe)
        self.label.setGeometry(QtCore.QRect(620, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.GRPAframe)
        self.label_2.setGeometry(QtCore.QRect(340, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.GRPAframe)
        self.label_3.setGeometry(QtCore.QRect(720, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.SEMPHYlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMPHYlineEdit.setGeometry(QtCore.QRect(780, 120, 131, 31))
        self.SEMPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMPHYlineEdit.setObjectName(_fromUtf8("SEMPHYlineEdit"))
        self.label_4 = QtGui.QLabel(self.GRPAframe)
        self.label_4.setGeometry(QtCore.QRect(920, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.PHYSICSLBL_2 = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL_2.setGeometry(QtCore.QRect(500, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL_2.setFont(font)
        self.PHYSICSLBL_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL_2.setObjectName(_fromUtf8("PHYSICSLBL_2"))
        self.ATTPHYLBL_2 = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL_2.setGeometry(QtCore.QRect(40, 220, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL_2.setFont(font)
        self.ATTPHYLBL_2.setObjectName(_fromUtf8("ATTPHYLBL_2"))
        self.ATTCHMlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTCHMlineEdit.setGeometry(QtCore.QRect(190, 220, 141, 31))
        self.ATTCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTCHMlineEdit.setObjectName(_fromUtf8("ATTCHMlineEdit"))
        self.label_5 = QtGui.QLabel(self.GRPAframe)
        self.label_5.setGeometry(QtCore.QRect(340, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.UTLBL_2 = QtGui.QLabel(self.GRPAframe)
        self.UTLBL_2.setGeometry(QtCore.QRect(430, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL_2.setFont(font)
        self.UTLBL_2.setObjectName(_fromUtf8("UTLBL_2"))
        self.UTCHMlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTCHMlineEdit.setGeometry(QtCore.QRect(480, 220, 131, 31))
        self.UTCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTCHMlineEdit.setObjectName(_fromUtf8("UTCHMlineEdit"))
        self.label_6 = QtGui.QLabel(self.GRPAframe)
        self.label_6.setGeometry(QtCore.QRect(620, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.GRPAframe)
        self.label_7.setGeometry(QtCore.QRect(730, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.SEMCHMlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMCHMlineEdit.setGeometry(QtCore.QRect(780, 220, 131, 31))
        self.SEMCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMCHMlineEdit.setObjectName(_fromUtf8("SEMCHMlineEdit"))
        self.label_8 = QtGui.QLabel(self.GRPAframe)
        self.label_8.setGeometry(QtCore.QRect(920, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.GRPAframe)
        self.label_9.setGeometry(QtCore.QRect(1000, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.GRADEPHYlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.GRADEPHYlineEdit.setGeometry(QtCore.QRect(1080, 120, 131, 31))
        self.GRADEPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEPHYlineEdit.setObjectName(_fromUtf8("GRADEPHYlineEdit"))
        self.label_10 = QtGui.QLabel(self.GRPAframe)
        self.label_10.setGeometry(QtCore.QRect(1010, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.GRADECHMlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.GRADECHMlineEdit.setGeometry(QtCore.QRect(1080, 220, 131, 31))
        self.GRADECHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADECHMlineEdit.setObjectName(_fromUtf8("GRADECHMlineEdit"))
        self.PHYSICSLBL_3 = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL_3.setGeometry(QtCore.QRect(510, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL_3.setFont(font)
        self.PHYSICSLBL_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL_3.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL_3.setObjectName(_fromUtf8("PHYSICSLBL_3"))
        self.PHYSICSLBL_4 = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL_4.setGeometry(QtCore.QRect(510, 380, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL_4.setFont(font)
        self.PHYSICSLBL_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL_4.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL_4.setObjectName(_fromUtf8("PHYSICSLBL_4"))
        self.PHYSICSLBL_5 = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL_5.setGeometry(QtCore.QRect(510, 470, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL_5.setFont(font)
        self.PHYSICSLBL_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL_5.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL_5.setObjectName(_fromUtf8("PHYSICSLBL_5"))
        self.PHYSICSLBL_6 = QtGui.QLabel(self.GRPAframe)
        self.PHYSICSLBL_6.setGeometry(QtCore.QRect(460, 560, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PHYSICSLBL_6.setFont(font)
        self.PHYSICSLBL_6.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.PHYSICSLBL_6.setAlignment(QtCore.Qt.AlignCenter)
        self.PHYSICSLBL_6.setObjectName(_fromUtf8("PHYSICSLBL_6"))
        self.SUBMITApushButton = QtGui.QPushButton(self.GRPAframe)
        self.SUBMITApushButton.setGeometry(QtCore.QRect(1000, 710, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMITApushButton.setFont(font)
        self.SUBMITApushButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.SUBMITApushButton.setObjectName(_fromUtf8("SUBMITApushButton"))
        ############################################################3
        self.SUBMITApushButton.clicked.connect(self.SUBMITApushButtonCheck)
        self.CLEARApushButton = QtGui.QPushButton(self.GRPAframe)
        self.CLEARApushButton.setGeometry(QtCore.QRect(1160, 710, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CLEARApushButton.setFont(font)
        self.CLEARApushButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.CLEARApushButton.setObjectName(_fromUtf8("CLEARApushButton"))
        self.ATTMATHlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTMATHlineEdit.setGeometry(QtCore.QRect(190, 330, 141, 31))
        self.ATTMATHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTMATHlineEdit.setObjectName(_fromUtf8("ATTMATHlineEdit"))
        self.UTMATHlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTMATHlineEdit.setGeometry(QtCore.QRect(480, 330, 141, 31))
        self.UTMATHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTMATHlineEdit.setObjectName(_fromUtf8("UTMATHlineEdit"))
        self.SEMMATHlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMMATHlineEdit.setGeometry(QtCore.QRect(780, 330, 141, 31))
        self.SEMMATHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMMATHlineEdit.setObjectName(_fromUtf8("SEMMATHlineEdit"))
        self.GRADEMATHlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.GRADEMATHlineEdit.setGeometry(QtCore.QRect(1080, 330, 141, 31))
        self.GRADEMATHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEMATHlineEdit.setObjectName(_fromUtf8("GRADEMATHlineEdit"))
        self.ATTBElineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTBElineEdit.setGeometry(QtCore.QRect(190, 420, 141, 31))
        self.ATTBElineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTBElineEdit.setObjectName(_fromUtf8("ATTBElineEdit"))
        self.UTBElineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTBElineEdit.setGeometry(QtCore.QRect(490, 420, 141, 31))
        self.UTBElineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTBElineEdit.setObjectName(_fromUtf8("UTBElineEdit"))
        self.SEMBElineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMBElineEdit.setGeometry(QtCore.QRect(790, 420, 141, 31))
        self.SEMBElineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMBElineEdit.setObjectName(_fromUtf8("SEMBElineEdit"))
        self.GRADEBElineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.GRADEBElineEdit.setGeometry(QtCore.QRect(1080, 420, 141, 31))
        self.GRADEBElineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEBElineEdit.setObjectName(_fromUtf8("GRADEBElineEdit"))
        self.ATTEGlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTEGlineEdit.setGeometry(QtCore.QRect(190, 520, 141, 31))
        self.ATTEGlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTEGlineEdit.setObjectName(_fromUtf8("ATTEGlineEdit"))
        self.UTEGlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTEGlineEdit.setGeometry(QtCore.QRect(490, 520, 141, 31))
        self.UTEGlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTEGlineEdit.setObjectName(_fromUtf8("UTEGlineEdit"))
        self.SEMEGlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMEGlineEdit.setGeometry(QtCore.QRect(790, 520, 141, 31))
        self.SEMEGlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMEGlineEdit.setObjectName(_fromUtf8("SEMEGlineEdit"))
        self.SEMEGlineEdit_2 = QtGui.QLineEdit(self.GRPAframe)
        self.SEMEGlineEdit_2.setGeometry(QtCore.QRect(1080, 520, 141, 31))
        self.SEMEGlineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMEGlineEdit_2.setObjectName(_fromUtf8("SEMEGlineEdit_2"))
        self.ATTCSlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.ATTCSlineEdit.setGeometry(QtCore.QRect(190, 630, 141, 31))
        self.ATTCSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTCSlineEdit.setObjectName(_fromUtf8("ATTCSlineEdit"))
        self.UTCSlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.UTCSlineEdit.setGeometry(QtCore.QRect(490, 630, 141, 31))
        self.UTCSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTCSlineEdit.setObjectName(_fromUtf8("UTCSlineEdit"))
        self.SEMCSlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.SEMCSlineEdit.setGeometry(QtCore.QRect(790, 630, 141, 31))
        self.SEMCSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMCSlineEdit.setObjectName(_fromUtf8("SEMCSlineEdit"))
        self.GRADECSlineEdit = QtGui.QLineEdit(self.GRPAframe)
        self.GRADECSlineEdit.setGeometry(QtCore.QRect(1080, 630, 141, 31))
        self.GRADECSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADECSlineEdit.setObjectName(_fromUtf8("GRADECSlineEdit"))
        self.ATTPHYLBL_3 = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL_3.setGeometry(QtCore.QRect(50, 330, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL_3.setFont(font)
        self.ATTPHYLBL_3.setObjectName(_fromUtf8("ATTPHYLBL_3"))
        self.ATTPHYLBL_4 = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL_4.setGeometry(QtCore.QRect(50, 420, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL_4.setFont(font)
        self.ATTPHYLBL_4.setObjectName(_fromUtf8("ATTPHYLBL_4"))
        self.ATTPHYLBL_5 = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL_5.setGeometry(QtCore.QRect(50, 520, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL_5.setFont(font)
        self.ATTPHYLBL_5.setObjectName(_fromUtf8("ATTPHYLBL_5"))
        self.ATTPHYLBL_6 = QtGui.QLabel(self.GRPAframe)
        self.ATTPHYLBL_6.setGeometry(QtCore.QRect(50, 630, 140, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ATTPHYLBL_6.setFont(font)
        self.ATTPHYLBL_6.setObjectName(_fromUtf8("ATTPHYLBL_6"))
        self.label_11 = QtGui.QLabel(self.GRPAframe)
        self.label_11.setGeometry(QtCore.QRect(340, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.GRPAframe)
        self.label_12.setGeometry(QtCore.QRect(340, 420, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.GRPAframe)
        self.label_13.setGeometry(QtCore.QRect(340, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.GRPAframe)
        self.label_14.setGeometry(QtCore.QRect(340, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.UTLBL_3 = QtGui.QLabel(self.GRPAframe)
        self.UTLBL_3.setGeometry(QtCore.QRect(430, 330, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL_3.setFont(font)
        self.UTLBL_3.setObjectName(_fromUtf8("UTLBL_3"))
        self.UTLBL_5 = QtGui.QLabel(self.GRPAframe)
        self.UTLBL_5.setGeometry(QtCore.QRect(440, 520, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL_5.setFont(font)
        self.UTLBL_5.setObjectName(_fromUtf8("UTLBL_5"))
        self.UTLBL_6 = QtGui.QLabel(self.GRPAframe)
        self.UTLBL_6.setGeometry(QtCore.QRect(440, 630, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL_6.setFont(font)
        self.UTLBL_6.setObjectName(_fromUtf8("UTLBL_6"))
        self.label_15 = QtGui.QLabel(self.GRPAframe)
        self.label_15.setGeometry(QtCore.QRect(630, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.GRPAframe)
        self.label_16.setGeometry(QtCore.QRect(640, 420, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.GRPAframe)
        self.label_17.setGeometry(QtCore.QRect(640, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.GRPAframe)
        self.label_18.setGeometry(QtCore.QRect(640, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.GRPAframe)
        self.label_19.setGeometry(QtCore.QRect(730, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.GRPAframe)
        self.label_20.setGeometry(QtCore.QRect(740, 420, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.GRPAframe)
        self.label_21.setGeometry(QtCore.QRect(740, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.GRPAframe)
        self.label_22.setGeometry(QtCore.QRect(740, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.GRPAframe)
        self.label_23.setGeometry(QtCore.QRect(930, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.GRPAframe)
        self.label_24.setGeometry(QtCore.QRect(940, 420, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.GRPAframe)
        self.label_25.setGeometry(QtCore.QRect(940, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.GRPAframe)
        self.label_26.setGeometry(QtCore.QRect(940, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.GRPAframe)
        self.label_27.setGeometry(QtCore.QRect(1010, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.GRPAframe)
        self.label_28.setGeometry(QtCore.QRect(1010, 420, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.GRPAframe)
        self.label_29.setGeometry(QtCore.QRect(1010, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.GRPAframe)
        self.label_30.setGeometry(QtCore.QRect(1010, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.UTLBL_4 = QtGui.QLabel(self.GRPAframe)
        self.UTLBL_4.setGeometry(QtCore.QRect(440, 420, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UTLBL_4.setFont(font)
        self.UTLBL_4.setObjectName(_fromUtf8("UTLBL_4"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.STUDENTDATALBL.setText(_translate("Dialog", "S T U D E N T   M A R K S   D A T A  ( F.Y.Btech  GROUP A )", None))
        self.STUDENTIDLBL.setText(_translate("Dialog", "STUDENT ID", None))
        self.PHYSICSLBL.setText(_translate("Dialog", "PHYSICS", None))
        self.DIVLBL.setText(_translate("Dialog", "DIV", None))
        self.ATTPHYLBL.setText(_translate("Dialog", "ATTENDANCE", None))
        self.UTLBL.setText(_translate("Dialog", "UT ", None))
        self.label.setText(_translate("Dialog", "/30", None))
        self.label_2.setText(_translate("Dialog", "/100", None))
        self.label_3.setText(_translate("Dialog", "SEM", None))
        self.label_4.setText(_translate("Dialog", "/70", None))
        self.PHYSICSLBL_2.setText(_translate("Dialog", "CHEMISTRY", None))
        self.ATTPHYLBL_2.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_5.setText(_translate("Dialog", "/100", None))
        self.UTLBL_2.setText(_translate("Dialog", "UT ", None))
        self.label_6.setText(_translate("Dialog", "/30", None))
        self.label_7.setText(_translate("Dialog", "SEM", None))
        self.label_8.setText(_translate("Dialog", "/70", None))
        self.label_9.setText(_translate("Dialog", "GRADE", None))
        self.label_10.setText(_translate("Dialog", "GRADE", None))
        self.PHYSICSLBL_3.setText(_translate("Dialog", "MATHEMATICS", None))
        self.PHYSICSLBL_4.setText(_translate("Dialog", "BEEE", None))
        self.PHYSICSLBL_5.setText(_translate("Dialog", "EG", None))
        self.PHYSICSLBL_6.setText(_translate("Dialog", "COMMUNICATION SKILL", None))
        self.SUBMITApushButton.setText(_translate("Dialog", "SUBMIT", None))
        self.CLEARApushButton.setText(_translate("Dialog", "CLEAR", None))
        self.ATTPHYLBL_3.setText(_translate("Dialog", "ATTENDANCE", None))
        self.ATTPHYLBL_4.setText(_translate("Dialog", "ATTENDANCE", None))
        self.ATTPHYLBL_5.setText(_translate("Dialog", "ATTENDANCE", None))
        self.ATTPHYLBL_6.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_11.setText(_translate("Dialog", "/100", None))
        self.label_12.setText(_translate("Dialog", "/100", None))
        self.label_13.setText(_translate("Dialog", "/100", None))
        self.label_14.setText(_translate("Dialog", "/100", None))
        self.UTLBL_3.setText(_translate("Dialog", "UT ", None))
        self.UTLBL_5.setText(_translate("Dialog", "UT ", None))
        self.UTLBL_6.setText(_translate("Dialog", "UT ", None))
        self.label_15.setText(_translate("Dialog", "/30", None))
        self.label_16.setText(_translate("Dialog", "/30", None))
        self.label_17.setText(_translate("Dialog", "/30", None))
        self.label_18.setText(_translate("Dialog", "/30", None))
        self.label_19.setText(_translate("Dialog", "SEM", None))
        self.label_20.setText(_translate("Dialog", "SEM", None))
        self.label_21.setText(_translate("Dialog", "SEM", None))
        self.label_22.setText(_translate("Dialog", "SEM", None))
        self.label_23.setText(_translate("Dialog", "/70", None))
        self.label_24.setText(_translate("Dialog", "/70", None))
        self.label_25.setText(_translate("Dialog", "/70", None))
        self.label_26.setText(_translate("Dialog", "/70", None))
        self.label_27.setText(_translate("Dialog", "GRADE", None))
        self.label_28.setText(_translate("Dialog", "GRADE", None))
        self.label_29.setText(_translate("Dialog", "GRADE", None))
        self.label_30.setText(_translate("Dialog", "GRADE", None))
        self.UTLBL_4.setText(_translate("Dialog", "UT ", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

