# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GRPB.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sqlite3

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog3(object):
    def showMessageBox(self,message):
        msgBox = QtGui.QMessageBox()
        msgBox.setIcon(QtGui.QMessageBox.Warning)
        
        msgBox.setText(message)
        msgBox.setStandardButtons(QtGui.QMessageBox.Ok)
        msgBox.exec_()
    def SUBMITBpushButtonCheck(self):
        
        self.showMessageBox('SUCCESSFULLY ENTERED MARKS')
    
    
        STUDENT_ID = self.STUDENTIDlineEdit.text()
        DIV = self.DIVlineEdit.text()
        ############################ PHYSICS 
        ATTPHY= self.ATTPHYlineEdit.text()
        UTPHY=self.UTPHYlineEdit.text()
        SEMPHY=self.SEMPHYlineEdit.text()
        GRADEPHY=self.GRADEPHYlineEdit.text()
        ############################ CHEMISTRY
        ATTCHEM= self.ATTCHMlineEdit.text()
        UTCHEM=self.UTCHMlineEdit.text()
        SEMCHEM=self.SEMCHMlineEdit.text()
        GRADECHEM=self.GRADECHMlineEdit.text()
        ############################ MATHS
        ATTMAT= self.ATTMATlineEdit.text()
        UTMAT=self.UTMATlineEdit.text()
        SEMMAT=self.SEMMATlineEdit.text()
        GRADEMAT=self.GRADEMATlineEdit.text()
        ############################ BEEE
        ATTFCP= self.ATTFCPlineEdit.text()
        UTFCP=self.UTFCPlineEdit.text()
        SEMFCP=self.SEMFCPlineEdit.text()
        GRADEFCP=self.GRADEFCPlineEdit.text()
        ############################ EG
        ATTMECH= self.ATTMECHlineEdit.text()
        UTMECH=self.UTMECHlineEdit.text()
        SEMMECH=self.SEMMECHlineEdit.text()
        GRADEMECH=self.SEMMECHlineEdit.text()
        ############################ CS
        ATTEVS= self.ATTEVSlineEdit.text()
        UTEVS=self.UTEVSlineEdit.text()
        SEMEVS=self.SEMEVSlineEdit.text()
        GRADEEVS=self.GRADEEVSlineEdit.text()
        

        connection  = sqlite3.connect("FYBTECH_B.db")
        connection.execute("INSERT INTO PHYSICS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTPHY,UTPHY,SEMPHY,GRADEPHY))
        connection.execute("INSERT INTO MATHS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTCHEM,UTCHEM,SEMCHEM,GRADECHEM))
        connection.execute("INSERT INTO CHEMISTRY VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTMAT,UTMAT,SEMMAT,GRADEMAT))
        connection.execute("INSERT INTO FCP VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTFCP,UTFCP,SEMFCP,GRADEFCP))
        connection.execute("INSERT INTO MECH VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTMECH,UTMECH,SEMMECH,GRADEMECH))
        connection.execute("INSERT INTO EVS VALUES(?,?,?,?,?,?)",(STUDENT_ID,DIV,ATTEVS,UTEVS,SEMEVS,GRADEEVS))                                                         
        connection.commit()
        connection.close()
        self.SUBMITBpushButton.show()

    
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1324, 894)
        Dialog.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 20, 1081, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 170, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 110, 1261, 721))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(750, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.STUDENTIDlineEdit = QtGui.QLineEdit(self.frame)
        self.STUDENTIDlineEdit.setGeometry(QtCore.QRect(180, 31, 321, 31))
        self.STUDENTIDlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.STUDENTIDlineEdit.setObjectName(_fromUtf8("STUDENTTIDlineEdit"))
        self.DIVlineEdit = QtGui.QLineEdit(self.frame)
        self.DIVlineEdit.setGeometry(QtCore.QRect(850, 30, 321, 31))
        self.DIVlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.DIVlineEdit.setObjectName(_fromUtf8("NAMElineEdit"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(570, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(400, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(700, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(960, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ATTPHYlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTPHYlineEdit.setGeometry(QtCore.QRect(170, 120, 211, 31))
        self.ATTPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTPHYlineEdit.setObjectName(_fromUtf8("ATTPHYBlineEdit"))
        self.UTPHYlineEdit = QtGui.QLineEdit(self.frame)
        self.UTPHYlineEdit.setGeometry(QtCore.QRect(460, 120, 211, 31))
        self.UTPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTPHYlineEdit.setObjectName(_fromUtf8("UTPHYBlineEdit"))
        self.SEMPHYlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMPHYlineEdit.setGeometry(QtCore.QRect(750, 120, 211, 31))
        self.SEMPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMPHYlineEdit.setObjectName(_fromUtf8("SEMPHYBlineEdit"))
        self.GRADEPHYlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADEPHYlineEdit.setGeometry(QtCore.QRect(1050, 120, 201, 31))
        self.GRADEPHYlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEPHYlineEdit.setObjectName(_fromUtf8("GRADEPHYBlineEdit"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(570, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(560, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(590, 370, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(570, 480, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(610, 600, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(30, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(30, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(30, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(30, 550, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 640, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(400, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(400, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(400, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(400, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(400, 640, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(700, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(700, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(700, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(710, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(710, 650, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(970, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(970, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(970, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(980, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(980, 650, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.ATTCHMlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTCHMlineEdit.setGeometry(QtCore.QRect(170, 210, 211, 31))
        self.ATTCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTCHMlineEdit.setObjectName(_fromUtf8("ATTCHMBlineEdit"))
        self.UTCHMlineEdit = QtGui.QLineEdit(self.frame)
        self.UTCHMlineEdit.setGeometry(QtCore.QRect(460, 210, 211, 31))
        self.UTCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTCHMlineEdit.setObjectName(_fromUtf8("UTCHMBlineEdit"))
        self.SEMCHMlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMCHMlineEdit.setGeometry(QtCore.QRect(750, 220, 211, 31))
        self.SEMCHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMCHMlineEdit.setObjectName(_fromUtf8("SEMCHMBlineEdit"))
        self.GRADECHMlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADECHMlineEdit.setGeometry(QtCore.QRect(1050, 210, 201, 31))
        self.GRADECHMlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADECHMlineEdit.setObjectName(_fromUtf8("GRADECHMBlineEdit"))
        self.ATTMATlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTMATlineEdit.setGeometry(QtCore.QRect(170, 320, 211, 31))
        self.ATTMATlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTMATlineEdit.setObjectName(_fromUtf8("ATTMATBlineEdit"))
        self.UTMATlineEdit = QtGui.QLineEdit(self.frame)
        self.UTMATlineEdit.setGeometry(QtCore.QRect(460, 320, 211, 31))
        self.UTMATlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTMATlineEdit.setObjectName(_fromUtf8("UTMATBlineEdit"))
        self.SEMMATlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMMATlineEdit.setGeometry(QtCore.QRect(750, 310, 211, 31))
        self.SEMMATlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMMATlineEdit.setObjectName(_fromUtf8("SEMMATBlineEdit"))
        self.GRADEMATlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADEMATlineEdit.setGeometry(QtCore.QRect(1050, 310, 201, 31))
        self.GRADEMATlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEMATlineEdit.setObjectName(_fromUtf8("GRADEMATBlineEdit"))
        self.ATTFCPlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTFCPlineEdit.setGeometry(QtCore.QRect(170, 420, 211, 31))
        self.ATTFCPlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTFCPlineEdit.setObjectName(_fromUtf8("ATTFCPBlineEdit"))
        self.UTFCPlineEdit = QtGui.QLineEdit(self.frame)
        self.UTFCPlineEdit.setGeometry(QtCore.QRect(460, 410, 211, 31))
        self.UTFCPlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTFCPlineEdit.setObjectName(_fromUtf8("UTFCPBlineEdit"))
        self.SEMFCPlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMFCPlineEdit.setGeometry(QtCore.QRect(750, 410, 211, 31))
        self.SEMFCPlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMFCPlineEdit.setObjectName(_fromUtf8("SEMFCPBlineEdit"))
        self.GRADEFCPlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADEFCPlineEdit.setGeometry(QtCore.QRect(1060, 400, 191, 31))
        self.GRADEFCPlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEFCPlineEdit.setObjectName(_fromUtf8("GRADEFCPBlineEdit"))
        self.ATTMECHlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTMECHlineEdit.setGeometry(QtCore.QRect(170, 550, 211, 31))
        self.ATTMECHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTMECHlineEdit.setObjectName(_fromUtf8("ATTMECHBlineEdit"))
        self.UTMECHlineEdit = QtGui.QLineEdit(self.frame)
        self.UTMECHlineEdit.setGeometry(QtCore.QRect(460, 540, 211, 31))
        self.UTMECHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTMECHlineEdit.setObjectName(_fromUtf8("UTMECHBlineEdit"))
        self.SEMMECHlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMMECHlineEdit.setGeometry(QtCore.QRect(760, 540, 211, 31))
        self.SEMMECHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMMECHlineEdit.setObjectName(_fromUtf8("SEMMECHBlineEdit"))
        self.GRADEMECHlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADEMECHlineEdit.setGeometry(QtCore.QRect(1050, 530, 201, 31))
        self.GRADEMECHlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEMECHlineEdit.setObjectName(_fromUtf8("GRADEMECHBlineEdit"))
        self.ATTEVSlineEdit = QtGui.QLineEdit(self.frame)
        self.ATTEVSlineEdit.setGeometry(QtCore.QRect(170, 640, 211, 31))
        self.ATTEVSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.ATTEVSlineEdit.setObjectName(_fromUtf8("ATTEVSBlineEdit"))
        self.UTEVSlineEdit = QtGui.QLineEdit(self.frame)
        self.UTEVSlineEdit.setGeometry(QtCore.QRect(460, 640, 211, 31))
        self.UTEVSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.UTEVSlineEdit.setObjectName(_fromUtf8("UTEVSBlineEdit"))
        self.SEMEVSlineEdit = QtGui.QLineEdit(self.frame)
        self.SEMEVSlineEdit.setGeometry(QtCore.QRect(760, 640, 211, 31))
        self.SEMEVSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.SEMEVSlineEdit.setObjectName(_fromUtf8("SEMEVSBlineEdit"))
        self.GRADEEVSlineEdit = QtGui.QLineEdit(self.frame)
        self.GRADEEVSlineEdit.setGeometry(QtCore.QRect(1060, 650, 191, 31))
        self.GRADEEVSlineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.GRADEEVSlineEdit.setObjectName(_fromUtf8("GRADEEVSBlineEdit"))
        self.SUBMITBpushButton = QtGui.QPushButton(Dialog)
        self.SUBMITBpushButton.setGeometry(QtCore.QRect(880, 837, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMITBpushButton.setFont(font)
        self.SUBMITBpushButton.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 255, 255);"))
        self.SUBMITBpushButton.setObjectName(_fromUtf8("SUBMITBpushButton"))
        ###################################################
        self.SUBMITBpushButton.clicked.connect(self.SUBMITBpushButtonCheck)
        self.CLEARBpushButton = QtGui.QPushButton(Dialog)
        self.CLEARBpushButton.setGeometry(QtCore.QRect(1080, 840, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Felix Titling"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CLEARBpushButton.setFont(font)
        self.CLEARBpushButton.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 255, 255);"))
        self.CLEARBpushButton.setObjectName(_fromUtf8("CLEARBpushButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "S T U D E N T   M A R K S   D E T A I  L S      ( F. Y . Btech   G R O U P    B)", None))
        self.label_2.setText(_translate("Dialog", " STUDENT ID ", None))
        self.label_3.setText(_translate("Dialog", "DIV", None))
        self.label_4.setText(_translate("Dialog", "PHYSICS", None))
        self.label_5.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_6.setText(_translate("Dialog", "UT", None))
        self.label_7.setText(_translate("Dialog", "SEM", None))
        self.label_8.setText(_translate("Dialog", "GRADE", None))
        self.label_9.setText(_translate("Dialog", "CHEMISTRY", None))
        self.label_10.setText(_translate("Dialog", "MATHEMATICS", None))
        self.label_11.setText(_translate("Dialog", "FCP", None))
        self.label_12.setText(_translate("Dialog", "MECHANICS", None))
        self.label_13.setText(_translate("Dialog", "EVS", None))
        self.label_14.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_15.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_16.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_17.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_18.setText(_translate("Dialog", "ATTENDANCE", None))
        self.label_19.setText(_translate("Dialog", "UT", None))
        self.label_20.setText(_translate("Dialog", "UT", None))
        self.label_21.setText(_translate("Dialog", "UT", None))
        self.label_22.setText(_translate("Dialog", "UT", None))
        self.label_23.setText(_translate("Dialog", "UT", None))
        self.label_24.setText(_translate("Dialog", "SEM", None))
        self.label_25.setText(_translate("Dialog", "SEM", None))
        self.label_26.setText(_translate("Dialog", "SEM", None))
        self.label_27.setText(_translate("Dialog", "SEM", None))
        self.label_28.setText(_translate("Dialog", "SEM", None))
        self.label_29.setText(_translate("Dialog", "GRADE", None))
        self.label_30.setText(_translate("Dialog", "GRADE", None))
        self.label_31.setText(_translate("Dialog", "GRADE", None))
        self.label_32.setText(_translate("Dialog", "GRADE", None))
        self.label_33.setText(_translate("Dialog", "GRADE", None))
        self.SUBMITBpushButton.setText(_translate("Dialog", "SUBMIT", None))
        self.CLEARBpushButton.setText(_translate("Dialog", "CLEAR", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog3()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

